Repository ssg-240304-java2/final-bidssgket, pull requests merged in 2024-08, with the labels that each got.

#67 product regist
  src/main/java/com/ssg/bidssgket/common/domain/BaseTimeAndDeleteEntity.java
  src/main/java/com/ssg/bidssgket/common/domain/BaseTimeEntity.java
  src/main/java/com/ssg/bidssgket/global/config/NcpS3Config.java
  src/main/java/com/ssg/bidssgket/global/util/ncps3/FileDto.java
  src/main/java/com/ssg/bidssgket/global/util/ncps3/FileService.java
  src/main/java/com/ssg/bidssgket/global/util/test.java
  src/main/java/com/ssg/bidssgket/user/domain/member/domain/repository/MemberRepository.java
  src/main/java/com/ssg/bidssgket/user/domain/product/api/dto/request/RegistProductReqDto.java
  src/main/java/com/ssg/bidssgket/user/domain/product/application/NcpObjectStorageService.java
  src/main/java/com/ssg/bidssgket/user/domain/product/application/ProductService.java
  src/main/java/com/ssg/bidssgket/user/domain/product/view/ProductViewController.java
  src/main/java/com/ssg/bidssgket/user/domain/product/view/dto/response/ProductResDto.java
  src/main/resources/templates/user/fragments/header.html
  src/main/resources/templates/user/product/regist.html
  src/main/resources/templates/user/product/register.html
Labels: Feature

#68 Feature/auction
  src/main/java/com/ssg/bidssgket/user/domain/auction/common/AuctionReqDto.java
  src/main/java/com/ssg/bidssgket/user/domain/auction/domain/Auction.java
  src/main/java/com/ssg/bidssgket/user/domain/auction/domain/repository/AuctionRepository.java
  src/main/java/com/ssg/bidssgket/user/domain/auction/view/AuctionViewController.java
  src/main/java/com/ssg/bidssgket/user/domain/main/view/mainViewController.java
  src/main/resources/static/user/auction/css/auctionpage.css
  src/main/resources/static/user/auction/css/auctionregist.css
  src/main/resources/static/user/auction/css/mainpage.css
  src/main/resources/static/user/css/style.css
  src/main/resources/static/user/main/css/mainpage.css
  src/main/resources/static/user/main/images/ad1.png
  src/main/resources/static/user/main/images/ad2.png
  src/main/resources/static/user/main/images/black_filled_heart.png
  src/main/resources/static/user/main/images/empty_heart.png
  src/main/resources/static/user/main/images/empty_heart2.png
  src/main/resources/static/user/main/images/filled_heart.png
  src/main/resources/static/user/main/images/filled_pink_heart.png
  src/main/resources/static/user/main/images/heart.png
  src/main/resources/static/user/main/images/heart1.png
  src/main/resources/static/user/main/images/heart_transparent.png
  src/main/resources/static/user/main/images/kreambanner1.png
  src/main/resources/static/user/main/images/kreambanner2.png
  src/main/resources/static/user/main/images/pradabag.jpg
  src/main/resources/static/user/main/images/pradabag2.jpg
  src/main/resources/static/user/main/images/잡화.png
  src/main/resources/templates/user/auction/auctionMain.html
  src/main/resources/templates/user/auction/auctionregist.html
  src/main/resources/templates/user/fragments/header.html
  src/main/resources/templates/user/main/mainpage.html
Labels: Feature

#70 [Feat: member] 구글 소셜로그인
  build.gradle
  src/main/java/com/ssg/bidssgket/admin/view/admin/main/AdminMainViewController.java
  src/main/java/com/ssg/bidssgket/global/config/WebSecurityConfig.java
  src/main/java/com/ssg/bidssgket/user/domain/member/api/chat/Controller/ChatController.java
  src/main/java/com/ssg/bidssgket/user/domain/member/api/chat/Dto/ChatRequestDto.java
  src/main/java/com/ssg/bidssgket/user/domain/member/api/chat/config/WebSocketConfig.java
  src/main/java/com/ssg/bidssgket/user/domain/member/api/googleLogin/config/TokenAuthenticationFilter.java
  src/main/java/com/ssg/bidssgket/user/domain/member/api/googleLogin/config/jwt/JwtProperties.java
  src/main/java/com/ssg/bidssgket/user/domain/member/api/googleLogin/config/jwt/TokenProvider.java
  src/main/java/com/ssg/bidssgket/user/domain/member/api/googleLogin/config/oauth/OAuth2AuthorizationRequestBasedOnCookieRepository.java
  src/main/java/com/ssg/bidssgket/user/domain/member/api/googleLogin/config/oauth/OAuth2SuccessHandler.java
  src/main/java/com/ssg/bidssgket/user/domain/member/api/googleLogin/config/oauth/OAuth2UserCustomService.java
  src/main/java/com/ssg/bidssgket/user/domain/member/api/googleLogin/domain/RefreshToken.java
  src/main/java/com/ssg/bidssgket/user/domain/member/api/googleLogin/dto/CreateAccessTokenRequest.java
  src/main/java/com/ssg/bidssgket/user/domain/member/api/googleLogin/dto/CreateAccessTokenResponse.java
  src/main/java/com/ssg/bidssgket/user/domain/member/api/googleLogin/repository/RefreshTokenRepository.java
  src/main/java/com/ssg/bidssgket/user/domain/member/api/googleLogin/repository/UserRepository.java
  src/main/java/com/ssg/bidssgket/user/domain/member/api/googleLogin/service/RefreshTokenService.java
  src/main/java/com/ssg/bidssgket/user/domain/member/api/googleLogin/service/TokenService.java
  src/main/java/com/ssg/bidssgket/user/domain/member/api/googleLogin/service/UserService.java
  src/main/java/com/ssg/bidssgket/user/domain/member/api/googleLogin/util/CookieUtil.java
  src/main/java/com/ssg/bidssgket/user/domain/member/domain/HtmlTestController.java
  src/main/java/com/ssg/bidssgket/user/domain/member/domain/Member.java
  src/main/java/com/ssg/bidssgket/user/domain/member/domain/repository/MemberRepository.java
  src/main/java/com/ssg/bidssgket/user/domain/member/view/DTO/MemberDto.java
  src/main/resources/templates/user/fragments/header.html
  src/main/resources/templates/user/member/index.html
  src/main/resources/templates/user/member/info.html
  src/main/resources/templates/user/member/info_update.html
  src/main/resources/templates/user/member/login.html
  src/main/resources/templates/user/member/logout.html
  src/main/resources/templates/user/member/review.html
  src/main/resources/templates/user/member/review_buyer.private.html
  src/main/resources/templates/user/member/review_seller.admin.html
  src/main/resources/templates/user/member/wishlist.html
Labels: Feature

#77 feat:order-payment Order & Payment 화면 작성 및 페이지 연결
  src/main/java/com/ssg/bidssgket/user/domain/order/view/OrderViewController.java
  src/main/java/com/ssg/bidssgket/user/domain/order/view/PurchaseOrderViewController.java
  src/main/java/com/ssg/bidssgket/user/domain/order/view/SaleOrderViewController.java
  src/main/java/com/ssg/bidssgket/user/domain/payment/view/PaymentViewController.java
  src/main/resources/templates/user/fragments/header.html
  src/main/resources/templates/user/order/checkout.html
  src/main/resources/templates/user/order/mypage.html
  src/main/resources/templates/user/order/purchases/cancelled.html
  src/main/resources/templates/user/order/purchases/completed.html
  src/main/resources/templates/user/order/purchases/delivered.html
  src/main/resources/templates/user/order/purchases/history/auction.html
  src/main/resources/templates/user/order/purchases/history/completed.html
  src/main/resources/templates/user/order/purchases/history/progress.html
  src/main/resources/templates/user/order/purchases/pending.html
  src/main/resources/templates/user/order/purchases/shipping.html
  src/main/resources/templates/user/order/sales/cancelled.html
  src/main/resources/templates/user/order/sales/completed.html
  src/main/resources/templates/user/order/sales/delivered.html
  src/main/resources/templates/user/order/sales/history/auction.html
  src/main/resources/templates/user/order/sales/history/completed.html
  src/main/resources/templates/user/order/sales/history/progress.html
  src/main/resources/templates/user/order/sales/pending.html
  src/main/resources/templates/user/order/sales/shipping.html
  src/main/resources/templates/user/payment/deposit.html
  src/main/resources/templates/user/payment/info.html
  src/main/resources/templates/user/payment/withdrawal.html
Labels: Feature

#79 Feature/update
  build.gradle
  src/main/java/com/ssg/bidssgket/global/config/BeanConfiguration.java
  src/main/java/com/ssg/bidssgket/user/domain/member/domain/HtmlTestController.java
  src/main/java/com/ssg/bidssgket/user/domain/member/domain/repository/MemberRepository.java
  src/main/java/com/ssg/bidssgket/user/domain/product/application/ProductService.java
  src/main/java/com/ssg/bidssgket/user/domain/product/domain/Product.java
  src/main/java/com/ssg/bidssgket/user/domain/product/view/ProductViewController.java
  src/main/java/com/ssg/bidssgket/user/domain/product/view/dto/request/ProductReqDto.java
  src/main/java/com/ssg/bidssgket/user/domain/product/view/dto/response/ProductResDto.java
  src/main/resources/static/user/product/css/regist.css
  src/main/resources/templates/user/product/register.html
Labels: documentation

#82 feat: payment 카카오페이 API 테스트 및 비스킷 페이 충전 기능 구현
  src/main/java/com/ssg/bidssgket/user/domain/order/view/OrderViewController.java
  src/main/java/com/ssg/bidssgket/user/domain/payment/api/PaymentApiController.java
  src/main/java/com/ssg/bidssgket/user/domain/payment/api/controller/KakaoPayApiController.java
  src/main/java/com/ssg/bidssgket/user/domain/payment/api/dto/request/PaymentCreateForm.java
  src/main/java/com/ssg/bidssgket/user/domain/payment/api/dto/response/Amount.java
  src/main/java/com/ssg/bidssgket/user/domain/payment/api/dto/response/KakaoApproveResDto.java
  src/main/java/com/ssg/bidssgket/user/domain/payment/api/dto/response/KakaoReadyResDto.java
  src/main/java/com/ssg/bidssgket/user/domain/payment/api/repository/MemberTestRepository.java
  src/main/java/com/ssg/bidssgket/user/domain/payment/api/service/KakaoPayService.java
  src/main/java/com/ssg/bidssgket/user/domain/payment/api/service/MemberTestService.java
  src/main/java/com/ssg/bidssgket/user/domain/payment/application/PaymentService.java
  src/main/java/com/ssg/bidssgket/user/domain/payment/application/dto/response/ErrorResponse.java
  src/main/java/com/ssg/bidssgket/user/domain/payment/application/service/PayChangeService.java
  src/main/java/com/ssg/bidssgket/user/domain/payment/application/service/PayService.java
  src/main/java/com/ssg/bidssgket/user/domain/payment/application/service/PaymentService.java
  src/main/java/com/ssg/bidssgket/user/domain/payment/domain/Pay.java
  src/main/java/com/ssg/bidssgket/user/domain/payment/domain/PayChange.java
  src/main/java/com/ssg/bidssgket/user/domain/payment/domain/repository/PayChangeRepository.java
  src/main/java/com/ssg/bidssgket/user/domain/payment/domain/repository/PayRepository.java
  src/main/java/com/ssg/bidssgket/user/domain/payment/exception/BusinessLogicException.java
  src/main/java/com/ssg/bidssgket/user/domain/payment/exception/ExceptionCode.java
  src/main/java/com/ssg/bidssgket/user/domain/payment/exception/GlobalExceptionHandler.java
  src/main/java/com/ssg/bidssgket/user/util/SessionUtils.java
  src/main/resources/templates/user/fragments/header.html
  src/main/resources/templates/user/order/checkout.html
  src/main/resources/templates/user/order/mypage.html
  src/main/resources/templates/user/order/purchases/cancelled.html
  src/main/resources/templates/user/order/purchases/completed.html
  src/main/resources/templates/user/order/purchases/delivered.html
  src/main/resources/templates/user/order/purchases/history/auction.html
  src/main/resources/templates/user/order/purchases/history/completed.html
  src/main/resources/templates/user/order/purchases/history/progress.html
  src/main/resources/templates/user/order/purchases/pending.html
  src/main/resources/templates/user/order/purchases/shipping.html
  src/main/resources/templates/user/order/sales/cancelled.html
  src/main/resources/templates/user/order/sales/completed.html
  src/main/resources/templates/user/order/sales/delivered.html
  src/main/resources/templates/user/order/sales/history/auction.html
  src/main/resources/templates/user/order/sales/history/completed.html
  src/main/resources/templates/user/order/sales/history/progress.html
  src/main/resources/templates/user/order/sales/pending.html
  src/main/resources/templates/user/order/sales/shipping.html
  src/main/resources/templates/user/payment/deposit.html
  src/main/resources/templates/user/payment/info.html
  src/main/resources/templates/user/payment/withdrawal.html
Labels: Feature

#85 feat:order-payment HTML & CSS 수정
  src/main/resources/templates/user/order/purchases/completed.html
  src/main/resources/templates/user/order/purchases/delivered.html
  src/main/resources/templates/user/order/purchases/history/auction.html
  src/main/resources/templates/user/order/purchases/history/completed.html
  src/main/resources/templates/user/order/purchases/history/progress.html
  src/main/resources/templates/user/order/purchases/pending.html
  src/main/resources/templates/user/order/purchases/shipping.html
  src/main/resources/templates/user/order/sales/history/auction.html
  src/main/resources/templates/user/order/sales/history/completed.html
  src/main/resources/templates/user/order/sales/history/progress.html
  src/main/resources/templates/user/payment/info.html
Labels: fix

#86 Feature/update: 상품 수정 완료
  src/main/java/com/ssg/bidssgket/user/domain/product/api/ProductApiController.java
  src/main/java/com/ssg/bidssgket/user/domain/product/api/dto/request/RegistProductReqDto.java
  src/main/java/com/ssg/bidssgket/user/domain/product/api/dto/response/ProductApiResDto.java
  src/main/java/com/ssg/bidssgket/user/domain/product/application/ProductService.java
  src/main/java/com/ssg/bidssgket/user/domain/product/domain/Product.java
  src/main/java/com/ssg/bidssgket/user/domain/product/domain/ProductImage.java
  src/main/java/com/ssg/bidssgket/user/domain/product/domain/SalesStatus.java
  src/main/java/com/ssg/bidssgket/user/domain/product/domain/repository/ProductImageRepository.java
  src/main/java/com/ssg/bidssgket/user/domain/product/domain/repository/ProductRepository.java
  src/main/java/com/ssg/bidssgket/user/domain/product/view/ProductViewController.java
  src/main/java/com/ssg/bidssgket/user/domain/product/view/dto/request/ProductReqDto.java
  src/main/java/com/ssg/bidssgket/user/domain/product/view/dto/response/ProductResDto.java
  src/main/java/com/ssg/bidssgket/user/domain/product/view/dto/response/productImageDto.java
  src/main/resources/application.yml
  src/main/resources/static/user/css/style.css
  src/main/resources/static/user/product/css/update.css
  src/main/resources/templates/user/fragments/header.html
  src/main/resources/templates/user/product/detailAuction.html
  src/main/resources/templates/user/product/register.html
  src/main/resources/templates/user/product/update.html
Labels: Feature

#88 Feature/auction 경매 등록, 수정, 삭제
  src/main/java/com/ssg/bidssgket/global/config/WebSecurityConfig.java
  src/main/java/com/ssg/bidssgket/user/domain.zip
  src/main/java/com/ssg/bidssgket/user/domain/auction/api/AuctionApiController.java
  src/main/java/com/ssg/bidssgket/user/domain/auction/application/AuctionService.java
  src/main/java/com/ssg/bidssgket/user/domain/auction/domain/Auction.java
  src/main/java/com/ssg/bidssgket/user/domain/auction/domain/auctiondummy.sql
  src/main/java/com/ssg/bidssgket/user/domain/auction/domain/dto/AuctionReqDto.java
  src/main/java/com/ssg/bidssgket/user/domain/auction/domain/dto/AuctionResponseDto.java
  src/main/java/com/ssg/bidssgket/user/domain/auction/domain/repository/AuctionRepository.java
  src/main/java/com/ssg/bidssgket/user/domain/auction/view/AuctionViewController.java
  src/main/resources/static/user/auction/css/auctionregist.css
  src/main/resources/static/user/main/css/mainpage.css
  src/main/resources/templates/user/auction/auctionregist.html
  src/main/resources/templates/user/auction/auctionregistmodify.html
  src/main/resources/templates/user/product/detailAuction.html
  src/main/resources/templates/user/product/detailBuyer.html
Labels: enhancement

#89 Feature: 상품 상세 조회
  src/main/java/com/ssg/bidssgket/user/domain/auction/domain/repository/AuctionRepository.java
  src/main/java/com/ssg/bidssgket/user/domain/main/view/mainViewController.java
  src/main/java/com/ssg/bidssgket/user/domain/product/api/ProductApiController.java
  src/main/java/com/ssg/bidssgket/user/domain/product/api/dto/request/RegistProductReqDto.java
  src/main/java/com/ssg/bidssgket/user/domain/product/application/ProductService.java
  src/main/java/com/ssg/bidssgket/user/domain/product/domain/repository/ProductRepository.java
  src/main/java/com/ssg/bidssgket/user/domain/product/view/ProductViewController.java
  src/main/resources/templates/user/auction/auctionMain.html
  src/main/resources/templates/user/fragments/header.html
  src/main/resources/templates/user/main/mainpage.html
  src/main/resources/templates/user/product/detailAuction.html
  src/main/resources/templates/user/product/detailBuyer.html
  src/main/resources/templates/user/product/detailSeller.html
  src/main/resources/templates/user/product/list.html
  src/main/resources/templates/user/product/register.html
Labels: Feature

#90 Feat: 상품 조회
  src/main/resources/static/user/main/css/mainpage.css
  src/main/resources/templates/user/fragments/header.html
  src/main/resources/templates/user/main/mainpage.html
  src/main/resources/templates/user/product/category.html
  src/main/resources/templates/user/product/list.html
Labels: Feature

#102 Feature/auction 경매 낙찰 로직
  src/main/java/com/ssg/bidssgket/user/domain/auction/application/AuctionService.java
  src/main/java/com/ssg/bidssgket/user/domain/auction/domain/Auction.java
  src/main/java/com/ssg/bidssgket/user/domain/auction/domain/repository/AuctionRepository.java
  src/main/java/com/ssg/bidssgket/user/domain/auction/view/AuctionViewController.java
  src/main/java/com/ssg/bidssgket/user/domain/product/domain/repository/ProductRepository.java
  src/main/java/com/ssg/bidssgket/user/domain/product/view/ProductViewController.java
  src/main/java/com/ssg/bidssgket/user/domain/product/view/dto/response/ProductResDto.java
  src/main/resources/application.yml
  src/main/resources/static/user/product/css/detail_auction.css
  src/main/resources/templates/user/product/bidFailed.html
  src/main/resources/templates/user/product/bidSuccess.html
  src/main/resources/templates/user/product/detailAuction.html
  src/main/resources/templates/user/product/detailBuyer.html
  src/main/resources/templates/user/product/detailSeller.html
Labels: enhancement

#104 Feature/auction 유찰 상태 처리
  src/main/java/com/ssg/bidssgket/user/domain/auction/application/AuctionService.java
  src/main/java/com/ssg/bidssgket/user/domain/auction/view/AuctionViewController.java
  src/main/java/com/ssg/bidssgket/user/domain/auction/view/dto/FailedProductReqDto.java
  src/main/java/com/ssg/bidssgket/user/domain/product/application/ProductService.java
  src/main/resources/static/user/auction/css/bidfailedupdate.css
  src/main/resources/templates/user/auction/auctionregistmodify.html
  src/main/resources/templates/user/auction/bidfailedupdate.html
  src/main/resources/templates/user/product/bidFailed.html
  src/main/resources/templates/user/product/detailAuction.html
  src/main/resources/templates/user/product/detailBuyer.html
  src/main/resources/templates/user/product/detailSeller.html
Labels: enhancement

#107 Feature/auction 유찰된 상품 DB 삭제 처리
  src/main/java/com/ssg/bidssgket/user/domain/auction/application/AuctionService.java
  src/main/java/com/ssg/bidssgket/user/domain/auction/domain/dto/AuctionResponseDto.java
  src/main/java/com/ssg/bidssgket/user/domain/auction/view/AuctionViewController.java
  src/main/java/com/ssg/bidssgket/user/domain/member/domain/Member.java
  src/main/java/com/ssg/bidssgket/user/domain/product/view/ProductViewController.java
  src/main/resources/static/user/auction/css/auctionregist.css
  src/main/resources/templates/user/auction/auctionregistmodify.html
Labels: enhancement

#110 Feat: 실시간 경매
  build.gradle
  src/main/java/com/ssg/bidssgket/user/domain.zip
  src/main/java/com/ssg/bidssgket/user/domain/auction/application/AuctionService.java
  src/main/java/com/ssg/bidssgket/user/domain/auction/domain/repository/AuctionRepository.java
  src/main/java/com/ssg/bidssgket/user/domain/eventAuction/WebSocketConfig.java
  src/main/java/com/ssg/bidssgket/user/domain/eventAuction/WebSocketEventListener.java
  src/main/java/com/ssg/bidssgket/user/domain/eventAuction/api/EventAuctionApiController.java
  src/main/java/com/ssg/bidssgket/user/domain/eventAuction/application/EventAuctionService.java
  src/main/java/com/ssg/bidssgket/user/domain/eventAuction/view/EventAuctionViewController.java
  src/main/java/com/ssg/bidssgket/user/domain/eventAuction/view/LiveAuctionController.java
  src/main/java/com/ssg/bidssgket/user/domain/eventAuction/view/dto/BidMessage.java
  src/main/java/com/ssg/bidssgket/user/domain/member/api/chat/websocket/WebSocketConfig.java
  src/main/java/com/ssg/bidssgket/user/domain/member/api/chat/websocket/WebSocketEventListener.java
  src/main/java/com/ssg/bidssgket/user/domain/product/application/ProductService.java
  src/main/java/com/ssg/bidssgket/user/domain/product/domain/Product.java
  src/main/resources/templates/index.html
  src/main/resources/templates/user/auction/auctionMain.html
  src/main/resources/templates/user/auction/auctionregist.html
  src/main/resources/templates/user/auction/auctionregistmodify.html
  src/main/resources/templates/user/eventAuction/detailAuction.html
  src/main/resources/templates/user/eventAuction/detailBuyer.html
  src/main/resources/templates/user/eventAuction/detailSeller.html
  src/main/resources/templates/user/eventAuction/lists.html
  src/main/resources/templates/user/main/mainpage.html
  src/main/resources/templates/user/member/index.html
  src/main/resources/templates/user/member/wishlist.html
  src/main/resources/templates/user/product/category.html
  src/main/resources/templates/user/product/list.html
Labels: Feature

#112 Feat: 실시간 경매(번개 경매)
  src/main/java/com/ssg/bidssgket/user/domain/auction/application/AuctionService.java
  src/main/java/com/ssg/bidssgket/user/domain/eventAuction/view/EventAuctionViewController.java
  src/main/java/com/ssg/bidssgket/user/domain/eventAuction/view/LiveAuctionController.java
  src/main/java/com/ssg/bidssgket/user/domain/member/api/chat/controller/ChatController.java
  src/main/resources/templates/user/eventAuction/bidFailed.html
  src/main/resources/templates/user/eventAuction/bidSuccess.html
  src/main/resources/templates/user/eventAuction/detailBuyer.html
  src/main/resources/templates/user/eventAuction/detailSeller.html
  src/main/resources/templates/user/member/chat.html
  src/main/resources/templates/user/product/bidFailed.html
  src/main/resources/templates/user/product/bidSuccess.html
  src/main/resources/templates/user/product/detailAuction.html
  src/main/resources/templates/user/product/detailBuyer.html
  src/main/resources/templates/user/product/detailSeller.html
Labels: Feature

#113 [Feature/위시리스트] 위시리스트 추가 및 삭제
  src/main/java/com/ssg/bidssgket/global/config/WebSecurityConfig.java
  src/main/java/com/ssg/bidssgket/user/domain/auction/application/AuctionService.java
  src/main/java/com/ssg/bidssgket/user/domain/auction/domain/dto/AuctionResponseDto.java
  src/main/java/com/ssg/bidssgket/user/domain/auction/view/AuctionViewController.java
  src/main/java/com/ssg/bidssgket/user/domain/main/view/mainViewController.java
  src/main/java/com/ssg/bidssgket/user/domain/member/domain/repository/MemberRepository.java
  src/main/java/com/ssg/bidssgket/user/domain/product/view/ProductViewController.java
  src/main/java/com/ssg/bidssgket/user/domain/productwish/application/ProductWishService.java
  src/main/java/com/ssg/bidssgket/user/domain/productwish/domain/dto/CheckDTO.java
  src/main/java/com/ssg/bidssgket/user/domain/productwish/domain/dto/MemberDTO.java
  src/main/java/com/ssg/bidssgket/user/domain/productwish/domain/dto/WishDTO.java
  src/main/java/com/ssg/bidssgket/user/domain/productwish/domain/repository/ProductWishRepository.java
  src/main/java/com/ssg/bidssgket/user/domain/productwish/view/WishSelectViewController.java
  src/main/resources/static/user/main/images/black_filled_heart.png
  src/main/resources/static/user/main/images/empty_heart.png
  src/main/resources/static/user/main/images/filled_heart.png
  src/main/resources/static/user/main/images/filled_pink_heart.png
  src/main/resources/static/user/main/images/heart1.png
  src/main/resources/static/user/main/images/heart_transparent.png
  src/main/resources/templates/user/main/mainpage.html
  src/main/resources/templates/user/product/bidFailed.html
  src/main/resources/templates/user/product/bidSuccess.html
  src/main/resources/templates/user/product/category.html
  src/main/resources/templates/user/product/list.html
Labels: Feature

#114 feat:payment 상품 결제 시 택배 배송 정보 Entity 추가 및 관계 설정 매핑 완료
  src/main/java/com/ssg/bidssgket/user/domain/member/domain/Member.java
  src/main/java/com/ssg/bidssgket/user/domain/order/application/OrderService.java
  src/main/java/com/ssg/bidssgket/user/domain/order/application/dto/request/DeliveryAddressReqDto.java
  src/main/java/com/ssg/bidssgket/user/domain/order/application/dto/response/DeliveryAddressResDto.java
  src/main/java/com/ssg/bidssgket/user/domain/order/domain/DeliveryAddress.java
  src/main/java/com/ssg/bidssgket/user/domain/payment/application/dto/request/PaymentReqDto.java
  src/main/java/com/ssg/bidssgket/user/domain/payment/application/dto/response/PayResDto.java
  src/main/java/com/ssg/bidssgket/user/domain/payment/application/service/PaymentService.java
  src/main/java/com/ssg/bidssgket/user/domain/payment/view/PaymentViewController.java
  src/main/java/com/ssg/bidssgket/user/domain/product/domain/Product.java
  src/main/resources/templates/user/payment/checkout.html
Labels: Feature

#115 Feature/경매 경매 조건 수정
  src/main/java/com/ssg/bidssgket/user/domain/auction/application/AuctionService.java
  src/main/java/com/ssg/bidssgket/user/domain/auction/domain/repository/AuctionRepository.java
  src/main/java/com/ssg/bidssgket/user/domain/auction/view/AuctionViewController.java
  src/main/java/com/ssg/bidssgket/user/domain/product/view/ProductViewController.java
  src/main/resources/templates/user/product/bidFailed.html
  src/main/resources/templates/user/product/detailAuction.html
  src/main/resources/templates/user/product/detailSeller.html
Labels: enhancement

#116 Feat: 실시간 채팅
  src/main/java/com/ssg/bidssgket/global/config/WebMvcConfig.java
  src/main/java/com/ssg/bidssgket/user/domain/eventAuction/view/EventAuctionViewController.java
  src/main/java/com/ssg/bidssgket/user/domain/eventAuction/view/LiveAuctionController.java
  src/main/java/com/ssg/bidssgket/user/domain/eventAuction/view/dto/BidMessage.java
  src/main/java/com/ssg/bidssgket/user/domain/main/view/mainViewController.java
  src/main/java/com/ssg/bidssgket/user/domain/member/api/chat/controller/ChatController.java
  src/main/java/com/ssg/bidssgket/user/domain/member/api/chat/controller/ChatMessageResDto.java
  src/main/java/com/ssg/bidssgket/user/domain/member/api/chat/service/ChatMessageService.java
  src/main/java/com/ssg/bidssgket/user/domain/member/api/chat/websocket/WebSocketConfig.java
  src/main/java/com/ssg/bidssgket/user/domain/member/api/chat/websocket/WebSocketEventListener.java
  src/main/resources/templates/user/eventAuction/detailBuyer.html
  src/main/resources/templates/user/eventAuction/detailSeller.html
  src/main/resources/templates/user/eventAuction/lists.html
  src/main/resources/templates/user/main/mainpage.html
  src/main/resources/templates/user/member/chat.html
  src/main/resources/templates/user/product/category.html
Labels: bug, Feature

#124 Feature/경매 경매 페이지 이동 수정
  src/main/java/com/ssg/bidssgket/user/domain/auction/application/AuctionService.java
  src/main/java/com/ssg/bidssgket/user/domain/auction/domain/Auction.java
  src/main/java/com/ssg/bidssgket/user/domain/auction/view/AuctionViewController.java
  src/main/java/com/ssg/bidssgket/user/domain/main/view/mainViewController.java
  src/main/java/com/ssg/bidssgket/user/domain/product/view/ProductViewController.java
  src/main/java/com/ssg/bidssgket/user/domain/productwish/application/ProductWishService.java
  src/main/java/com/ssg/bidssgket/user/domain/productwish/view/WishSelectViewController.java
  src/main/resources/static/user/main/css/mainpage.css
  src/main/resources/static/user/main/images/filled.png
  src/main/resources/static/user/main/images/redh.png
  src/main/resources/templates/user/main/mainpage.html
  src/main/resources/templates/user/product/category.html
  src/main/resources/templates/user/product/detailSeller.html
  src/main/resources/templates/user/product/list.html
Labels: enhancement

#126 Feature/위시리스트 위시리스트 버튼, script 수정
  src/main/java/com/ssg/bidssgket/user/domain/auction/view/AuctionViewController.java
  src/main/resources/templates/user/main/mainpage.html
  src/main/resources/templates/user/product/category.html
  src/main/resources/templates/user/product/list.html
Labels: bug, enhancement

#128 feat: Feature/payment 비스킷 페이로 상품 결제 기능 구현
  src/main/java/com/ssg/bidssgket/user/domain/auction/domain/Auction.java
  src/main/java/com/ssg/bidssgket/user/domain/auction/domain/repository/AuctionRepository.java
  src/main/java/com/ssg/bidssgket/user/domain/order/application/OrderService.java
  src/main/java/com/ssg/bidssgket/user/domain/order/application/PurchaseOrderService.java
  src/main/java/com/ssg/bidssgket/user/domain/order/application/SaleOrderService.java
  src/main/java/com/ssg/bidssgket/user/domain/order/application/dto/response/ProductWithOrderDto.java
  src/main/java/com/ssg/bidssgket/user/domain/order/domain/DeliveryAddress.java
  src/main/java/com/ssg/bidssgket/user/domain/order/domain/PurchaseOrder.java
  src/main/java/com/ssg/bidssgket/user/domain/order/domain/SaleOrder.java
  src/main/java/com/ssg/bidssgket/user/domain/order/domain/repository/DeliveryAddressRepository.java
  src/main/java/com/ssg/bidssgket/user/domain/order/domain/repository/OrderRepository.java
  src/main/java/com/ssg/bidssgket/user/domain/order/domain/repository/PurchaseOrderRepository.java
  src/main/java/com/ssg/bidssgket/user/domain/order/domain/repository/SaleOrderRepository.java
  src/main/java/com/ssg/bidssgket/user/domain/order/view/OrderViewController.java
  src/main/java/com/ssg/bidssgket/user/domain/order/view/PurchaseOrderViewController.java
  src/main/java/com/ssg/bidssgket/user/domain/order/view/SaleOrderViewController.java
  src/main/java/com/ssg/bidssgket/user/domain/payment/api/controller/KakaoPayApiController.java
  src/main/java/com/ssg/bidssgket/user/domain/payment/api/dto/request/PaymentCreateForm.java
  src/main/java/com/ssg/bidssgket/user/domain/payment/api/service/KakaoPayService.java
  src/main/java/com/ssg/bidssgket/user/domain/payment/application/dto/request/PaymentReqDto.java
  src/main/java/com/ssg/bidssgket/user/domain/payment/application/service/PaymentService.java
  src/main/java/com/ssg/bidssgket/user/domain/payment/view/PaymentViewController.java
  src/main/java/com/ssg/bidssgket/user/domain/product/application/ProductService.java
  src/main/java/com/ssg/bidssgket/user/domain/product/domain/Product.java
  src/main/resources/templates/user/auction/auctionMain.html
  src/main/resources/templates/user/eventAuction/lists.html
  src/main/resources/templates/user/order/mypage.html
  src/main/resources/templates/user/order/purchases/history/auction.html
  src/main/resources/templates/user/order/purchases/history/completed.html
  src/main/resources/templates/user/order/purchases/history/progress.html
  src/main/resources/templates/user/order/sales/history/auction.html
  src/main/resources/templates/user/payment/checkout.html
  src/main/resources/templates/user/payment/deposit.html
  src/main/resources/templates/user/payment/info.html
  src/main/resources/templates/user/product/detailBuyer.html
Labels: Feature

#142 Feat: 이미지 전송
  src/main/java/com/ssg/bidssgket/user/domain/main/view/mainViewController.java
  src/main/java/com/ssg/bidssgket/user/domain/member/api/chat/controller/ChatController.java
  src/main/java/com/ssg/bidssgket/user/domain/member/api/chat/controller/ChatMessageResDto.java
  src/main/java/com/ssg/bidssgket/user/domain/member/domain/Member.java
  src/main/java/com/ssg/bidssgket/user/domain/member/view/DTO/ChatMessageDto.java
  src/main/java/com/ssg/bidssgket/user/domain/product/view/ProductViewController.java
  src/main/resources/application.yml
  src/main/resources/static/user/member/chat.css
  src/main/resources/templates/user/auction/auctionMain.html
  src/main/resources/templates/user/eventAuction/lists.html
  src/main/resources/templates/user/eventAuction/regist.html
  src/main/resources/templates/user/member/chat.html
  src/main/resources/templates/user/product/category.html
  src/main/resources/templates/user/product/list.html
  src/main/resources/templates/user/product/register.html
Labels: enhancement, Feature

#143 [ Feature/UI ] 충돌 코드 정리
  src/main/resources/templates/user/main/mainpage.html
  src/main/resources/templates/user/product/bidFailed.html
  src/main/resources/templates/user/product/bidSuccess.html
  src/main/resources/templates/user/product/detailSeller.html
Labels: bug

#144 [Fix / UI] 조회 ui 수정 & 결제 연결
  src/main/java/com/ssg/bidssgket/global/config/StringToIntegerConverter.java
  src/main/java/com/ssg/bidssgket/global/config/WebMvcConfig.java
  src/main/java/com/ssg/bidssgket/user/domain/payment/view/PaymentViewController.java
  src/main/java/com/ssg/bidssgket/user/domain/product/api/ProductApiController.java
  src/main/java/com/ssg/bidssgket/user/domain/product/api/dto/request/RegistProductReqDto.java
  src/main/resources/templates/user/auction/auctionMain.html
  src/main/resources/templates/user/eventAuction/detailBuyer.html
  src/main/resources/templates/user/eventAuction/detailSeller.html
  src/main/resources/templates/user/eventAuction/lists.html
  src/main/resources/templates/user/eventAuction/regist.html
  src/main/resources/templates/user/main/mainpage.html
  src/main/resources/templates/user/payment/checkout.html
  src/main/resources/templates/user/product/bidSuccess.html
  src/main/resources/templates/user/product/category.html
  src/main/resources/templates/user/product/detailAuction.html
  src/main/resources/templates/user/product/detailBuyer.html
  src/main/resources/templates/user/product/detailSeller.html
  src/main/resources/templates/user/product/list.html
  src/main/resources/templates/user/product/register.html
Labels: fix

#146 Feature/pageuimodify 메인 UI 수정 및 숫자 단위 처리
  src/main/java/com/ssg/bidssgket/user/domain/auction/view/AuctionViewController.java
  src/main/resources/static/user/auction/css/auctionregist.css
  src/main/resources/static/user/main/css/mainpage.css
  src/main/resources/static/user/main/images/adbanner.jpg
  src/main/resources/static/user/main/images/adidas.jpg
  src/main/resources/static/user/main/images/arttoy.jpg
  src/main/resources/static/user/main/images/auction.jpg
  src/main/resources/static/user/main/images/autumn.jpg
  src/main/resources/static/user/main/images/bag.jpg
  src/main/resources/static/user/main/images/cameracateg.jpg
  src/main/resources/static/user/main/images/interior.jpg
  src/main/resources/static/user/main/images/kakaoad.png
  src/main/resources/static/user/main/images/kreambanner1.png
  src/main/resources/static/user/main/images/kreambanner2.png
  src/main/resources/static/user/main/images/sellingbanner.jpg
  src/main/resources/static/user/main/images/tradebanner.jpg
  src/main/resources/static/user/main/images/tradecard.png
  src/main/resources/static/user/main/images/unif.jpg
  src/main/resources/static/user/main/images/watch.jpg
  src/main/resources/static/user/main/images/watchbanner.jpg
  src/main/resources/templates/user/auction/auctionregist.html
  src/main/resources/templates/user/auction/auctionregistmodify.html
  src/main/resources/templates/user/main/mainpage.html
Labels: bug, enhancement

#147 경매 로직 수정
  src/main/java/com/ssg/bidssgket/user/domain/auction/application/AuctionService.java
  src/main/java/com/ssg/bidssgket/user/domain/auction/domain/repository/AuctionRepository.java
Labels: enhancement

#148 Feat: 결제, 구매 내역
  src/main/java/com/ssg/bidssgket/user/domain/auction/domain/repository/AuctionRepository.java
  src/main/java/com/ssg/bidssgket/user/domain/order/application/SaleOrderService.java
  src/main/java/com/ssg/bidssgket/user/domain/order/domain/PurchaseOrder.java
  src/main/java/com/ssg/bidssgket/user/domain/order/domain/repository/PurchaseOrderRepository.java
  src/main/java/com/ssg/bidssgket/user/domain/order/domain/repository/SaleOrderRepository.java
  src/main/java/com/ssg/bidssgket/user/domain/order/view/OrderViewController.java
  src/main/java/com/ssg/bidssgket/user/domain/order/view/SaleOrderViewController.java
  src/main/java/com/ssg/bidssgket/user/domain/payment/application/service/PaymentService.java
  src/main/java/com/ssg/bidssgket/user/domain/payment/domain/repository/PaymentRepository.java
  src/main/java/com/ssg/bidssgket/user/domain/payment/view/PaymentViewController.java
  src/main/java/com/ssg/bidssgket/user/domain/product/domain/Product.java
  src/main/java/com/ssg/bidssgket/user/domain/product/domain/repository/ProductRepository.java
  src/main/resources/templates/user/order/purchases/history/auction.html
  src/main/resources/templates/user/order/purchases/history/completed.html
  src/main/resources/templates/user/order/purchases/history/progress.html
  src/main/resources/templates/user/order/sales/history/auction.html
  src/main/resources/templates/user/order/sales/history/completed.html
  src/main/resources/templates/user/order/sales/history/progress.html
  src/main/resources/templates/user/payment/checkout.html
  src/main/resources/templates/user/payment/info.html
Labels: Feature, fix

#149 [ Feature/경매 ] 경매 입찰 등록 시 조건 추가
  src/main/java/com/ssg/bidssgket/user/domain/auction/application/AuctionService.java
  src/main/java/com/ssg/bidssgket/user/domain/auction/domain/repository/AuctionRepository.java
  src/main/java/com/ssg/bidssgket/user/domain/auction/view/AuctionViewController.java
  src/main/resources/templates/user/auction/auctionregist.html
Labels: fix

#151 fix: 경매Repo 수정
  src/main/java/com/ssg/bidssgket/user/domain/auction/application/AuctionService.java
  src/main/java/com/ssg/bidssgket/user/domain/auction/domain/repository/AuctionRepository.java
  src/main/java/com/ssg/bidssgket/user/domain/eventAuction/view/EventAuctionViewController.java
  src/main/java/com/ssg/bidssgket/user/domain/product/view/ProductViewController.java
  src/main/resources/static/user/product/css/regist.css
  src/main/resources/templates/user/eventAuction/regist.html
  src/main/resources/templates/user/order/purchases/history/auction.html
  src/main/resources/templates/user/order/purchases/history/completed.html
  src/main/resources/templates/user/order/purchases/history/progress.html
  src/main/resources/templates/user/order/sales/history/auction.html
  src/main/resources/templates/user/order/sales/history/completed.html
  src/main/resources/templates/user/order/sales/history/progress.html
  src/main/resources/templates/user/product/register.html
  src/main/resources/templates/user/product/update.html
Labels: fix

#153 fix:chat수정
  src/main/java/com/ssg/bidssgket/user/domain/member/api/chat/controller/ChatController.java
  src/main/java/com/ssg/bidssgket/user/domain/member/api/chat/repository/ChatRoomRepository.java
Labels: fix

#160 Fix : 실시간 경매 수정
  src/main/java/com/ssg/bidssgket/user/domain/auction/application/AuctionService.java
  src/main/java/com/ssg/bidssgket/user/domain/member/api/chat/controller/ChatController.java
  src/main/java/com/ssg/bidssgket/user/domain/payment/view/PaymentViewController.java
  src/main/resources/templates/user/product/bidFailed.html
  src/main/resources/templates/user/product/bidSuccess.html
Labels: fix
